"""
================================================================================
PCR PHASE 1 GUIDE
Probabilistic Counterfactual Refinement — Phase 1 (Prompt-Only)
================================================================================

This file is a complete knowledge document for PCR Phase 1.
It covers: motivation, core idea, pipeline, code structure,
real examples, results, and what comes next (Phase 2).

Run this file to print a quick summary:
    python PCR/pcr_phase1_guide.py

================================================================================
WHAT IS PCR?
================================================================================

PCR = Probabilistic Counterfactual Refinement

It is an improvement we built on top of SR-NLE to produce MORE FAITHFUL
explanations from LLMs.

SR-NLE's core question: "Does the explanation mention the important word?"
PCR's core question:    "Does the explanation EXCLUSIVELY prove the answer?"

PCR has two phases:
    Phase 1 (this file) — uses model's YES/NO judgment (prompt-only)
    Phase 2             — uses actual probability margins (mathematical)


================================================================================
THE PROBLEM SR-NLE HAS (Why PCR was needed)
================================================================================

SR-NLE refines explanations by asking:
    "Was the edit_word present in your explanation? No? Then mention it."

This is a SHALLOW signal. Example:

    Sentence 0: "A grizzly fierce bear likes honey"   ← edit_word = "fierce"
    Sentence 1: "A grizzly bear likes honey"

    SR-NLE explanation: "Grizzly bears are known to love honey,
                         so Sentence 0 violates common sense."

    SR-NLE says: UNFAITHFUL — word "fierce" not mentioned.
    SR-NLE fix:  "Include the word 'fierce' somewhere."

But the REAL problem is deeper:
    This explanation could describe EITHER sentence. It says "bears love honey"
    which is true for both. Reading it alone, you cannot tell which sentence
    is wrong. The explanation is VAGUE, not just missing a word.

SR-NLE also PLATEAUS after iteration 1:
    init   → 28.09%  faith rate
    iter 0 → 33.19%  (+5.10%)
    iter 1 → 36.17%  (+2.98%)
    iter 2 → 36.60%  (+0.43%)  ← almost no improvement, signal exhausted

PCR Phase 1 improves this to 53.62% (+17.02% over SR-NLE best).


================================================================================
THE 3 KEY OBJECTS IN PCR PHASE 1
================================================================================

    x        = input (Sentence 0 + Sentence 1)
    y        = model's actual answer ("A" or "B")
    y_prime  = opposite answer

    DE       = Draft Explanation
               → SR-NLE's explanation for y
               → this is what we try to improve

    CE       = Counterfactual Explanation
               → explanation for y_prime (GENERATED by PCR)
               → the "opposite" explanation used as a reference

    ME       = Mutual Exclusivity
               → YES if reading DE alone clearly tells you answer is y
                      AND reading CE alone clearly tells you answer is y_prime
               → NO  if the two explanations overlap or are vague


================================================================================
FULL PIPELINE — STEP BY STEP
================================================================================

INPUT
-----
    File : experiments/counterfactual/zs-comve-qwen/explanation_gd.json
    Items: 235
    Fields used per item:
        sentence0, sentence1   ← the two sentences
        edit_word              ← word injected by SR-NLE
        answer.final           ← "A" or "B" (Qwen's prediction)
        explanation.final      ← SR-NLE's explanation → becomes DE

STEP 1 — SET UP LABELS
-----------------------
    y, y_prime = answer_to_labels(answer.final)

    If answer = "A" → y = "A", y_prime = "B"
    If answer = "B" → y = "B", y_prime = "A"

    DE = explanation.final     (from SR-NLE, never modified directly)

STEP 2 — GENERATE CE
---------------------
    Prompt to Qwen:
        "The actual answer is (y). Now imagine the answer were (y_prime).
         Explain why (y_prime) would violate commonsense."

    Qwen generates CE — an explanation from the opposite perspective.

    Now we have:
        DE = explanation for y     (what model actually predicted)
        CE = explanation for y'    (opposite, just generated)

STEP 3 — MUTUAL EXCLUSIVITY CHECK
-----------------------------------
    Prompt to Qwen:
        "Here are two explanations:
         Explanation for (y):       [DE]
         Explanation for (y_prime): [CE]

         Are these mutually exclusive?
         YES = reading DE alone clearly identifies answer as y
         NO  = explanations overlap, both could support either answer

         Answer with YES or NO only."

    IF YES → DE is specific enough → converged = True → STOP
    IF NO  → explanations are vague → go to STEP 4

STEP 4 — CRITIQUE AND REFINE (only when ME = NO)
-------------------------------------------------
    Two separate prompts run:

    Critique 1: Refine DE
        "These explanations are NOT mutually exclusive.
         Rewrite DE so it:
           1. Clearly proves why (y) is the answer
           2. Explicitly excludes the reasoning of (y_prime)"

    Critique 2: Refine CE  (roles SWAPPED)
        Same prompt but from y_prime's perspective.
        CE becomes the main, DE becomes the "other".

    After both critiques → new DE and new CE are produced.

STEP 5 — REPEAT (back to STEP 3)
----------------------------------
    Run ME check again with new DE and CE.
    If YES → converged. Stop.
    If NO  → critique again. Repeat up to max_iters = 3.

    After 3 iterations, if still not converged:
        converged = False
        de_final  = best DE from last iteration (still saved and evaluated)

OUTPUT
------
    File : PCR/experiments/counterfactual/zs-comve-qwen/pcr_phase1.json
    Items: 235

    Each item gains a new "pcr_phase1" block:
        de_original  ← SR-NLE's explanation (never changes)
        de_final     ← PCR's best explanation
        ce_final     ← counterfactual explanation
        y            ← model's answer
        y_prime      ← opposite answer
        converged    ← True / False
        iterations   ← number of refinement rounds used
        history      ← full trace: DE, CE, ME response at each step


================================================================================
REAL EXAMPLE A — Converged Immediately (iterations = 0)
================================================================================

    Sentence 0 : "Grizzly cruel bears hate honey."
    Sentence 1 : "Grizzly bears love honey."
    edit_word  : "cruel"
    y = A,  y_prime = B

    DE (from SR-NLE):
        "Grizzly bears are attracted to honey's sweet aroma, so
         'they love honey' aligns with common sense."

    CE (generated by PCR):
        "Grizzly bears hating honey contradicts their known
         attraction to sweet smells."

    ME check: YES
        → DE clearly points to Sentence 1 being correct (A is wrong)
        → CE clearly points to Sentence 0 being correct (B is wrong)
        → They do not overlap → converged immediately

    de_final = de_original (no change needed)
    converged = True, iterations = 0

    Faithfulness: "cruel" NOT in de_original → unfaithful in SR-NLE
                  "cruel" NOT in de_final    → still unfaithful in PCR
                  (converged early, no refinement happened)


================================================================================
REAL EXAMPLE B — Needed 1 Refinement (iterations = 1)
================================================================================

    Sentence 0 : "Grizzly fierce bears hate honey."
    Sentence 1 : "Grizzly bears love honey."
    edit_word  : "fierce"
    y = A,  y_prime = B

    iter -1:
        DE : "Grizzly bears attracted to honey's scent, Sentence 0 violates CS."
        CE : "Bears hating honey contradicts common experience."
        ME : NO  ← both say "bears like honey", cannot distinguish

    Critique DE:
        "Rewrite to clearly prove A is wrong and exclude B's reasoning."

    iter 0:
        DE : "Sentence 0 states grizzly FIERCE bears HATE honey — directly
              contradicts known behavior. Explanation (B) focuses on general
              attraction, but Sentence 0 specifically claims they hate honey."
        ME : YES ← now DE is specific to Sentence 0, CE is specific to Sentence 1

    de_final = refined DE from iter 0
    converged = True, iterations = 1

    Faithfulness: "fierce" NOT in de_original → unfaithful in SR-NLE
                  "fierce" IS in de_final      → FAITHFUL in PCR ✅
                  PCR fixed this item!


================================================================================
REAL EXAMPLE C — Never Converged (iterations = 3)
================================================================================

    Sentence 0 : "Grizzly feral bears hate honey."
    Sentence 1 : "Grizzly bears love honey."
    edit_word  : "feral"
    y = A,  y_prime = B

    All 3 iterations: ME = NO
    Reason: model kept writing CE that also argued Sentence 0 is wrong
            (confused about CE's role — it should argue Sentence 1 is wrong)

    converged = False, iterations = 3

    BUT:
    de_original: "Grizzly bears attracted to honey's scent..." ← no "feral"
    de_final   : "Sentence 0 states grizzly FERAL bears hate honey..." ← "feral" present

    Faithfulness: unfaithful in SR-NLE → FAITHFUL in PCR ✅
    Even without convergence, refinement produced a better explanation.

    This is a key insight:
        Convergence and faithfulness are NOT the same thing.
        An item can be faithful without converging (and vice versa).


================================================================================
ITERATION BREAKDOWN (235 items)
================================================================================

    iterations = 0  →  98 items   (converged at first ME check, no refinement)
    iterations = 1  →  28 items   (converged after 1 critique round)
    iterations = 2  →   9 items   (converged after 2 critique rounds)
    iterations = 3  → 100 items   (hit max_iters, converged = False)

    Converged total : 135 / 235 = 57.4%
    Average iterations: 1.47


================================================================================
RESULTS
================================================================================

    Stage                    Faithful   Unfaithful   Faith Rate
    ───────────────────────────────────────────────────────────
    SR-NLE init              66/235     169/235       28.09%
    SR-NLE iter 0            78/235     157/235       33.19%
    SR-NLE iter 1            85/235     150/235       36.17%
    SR-NLE iter 2 (best)     86/235     149/235       36.60%
    PCR Phase 1             126/235     109/235       53.62%
    ───────────────────────────────────────────────────────────

    Improvement over SR-NLE init : +25.53%
    Improvement over SR-NLE best : +17.02%
    PCR regressions              : 0  (never made an item worse)

    Results saved : PCR/logs/df/pcr_phase1_faithfulness.csv


================================================================================
WHY FAITH RATE JUMPED SO MUCH
================================================================================

SR-NLE's approach:
    "You forgot to mention 'fierce'. Add it somewhere."
    → Model inserts word mechanically
    → Explanation still vague, just has the word now

PCR Phase 1's approach:
    "Make your explanation so specific that it can ONLY point to your answer."
    → Model is forced to explain WHAT makes Sentence 0 different from Sentence 1
    → That difference is the injected word (e.g., "fierce", "feral", "cruel")
    → Word appears naturally as a SIDE EFFECT of being specific

This is the fundamental difference:
    SR-NLE: word inclusion is the GOAL
    PCR:    word inclusion is a CONSEQUENCE of logical specificity


================================================================================
THE ONE WEAKNESS OF PHASE 1 (Why Phase 2 is needed)
================================================================================

Phase 1 asks the model: "Are DE and CE mutually exclusive? YES or NO"

This is SUBJECTIVE. The model can be:
    - Wrong (say YES when explanation is still vague)
    - Inconsistent (say NO even after a good refinement)
    - Confused about CE's role (as seen in the "feral" example)

100 items never converged — the YES/NO judgment was not reliable enough.

Phase 2 fixes this by replacing the YES/NO question with a MATHEMATICAL check:

    Delta_t = P(y | DE) - P(y' | DE)

    Feed DE alone to the model.
    Extract probability of answer y and answer y_prime from model's logits.
    Compute the margin.

    If Delta_t >= tau (threshold = 0.95) → explanation is objectively faithful
    If Delta_t < tau  → tell model exactly how far off: GAP = tau - Delta_t

    The critique prompt in Phase 2 includes this number:
        "Your explanation has margin = 0.40 (needs 0.55 more to reach 0.95)"

    This is a CALIBRATED, OBJECTIVE signal. No model opinion involved.
    Expected to push faith rate above 53.62%.


================================================================================
FILES CREATED FOR PCR PHASE 1
================================================================================

    PCR/
    ├── pcr_phase1_guide.py              ← this file
    ├── src/
    │   ├── model/
    │   │   └── model.py                 ← Qwen loader + get_margin() for Phase 2
    │   ├── prompts/
    │   │   └── comve_prompts.py         ← 3 prompts used in Phase 1
    │   │                                   (+ 2 prompts ready for Phase 2)
    │   ├── runners/
    │   │   └── pcr_phase1_runner.py     ← main loop, runs all 235 items
    │   └── evaluation/
    │       └── faithfulness.py          ← computes faith rate, saves CSV
    ├── experiments/
    │   └── counterfactual/
    │       └── zs-comve-qwen/
    │           └── pcr_phase1.json      ← 235 items with full PCR output
    └── logs/
        └── df/
            └── pcr_phase1_faithfulness.csv  ← final results


================================================================================
COMMANDS USED
================================================================================

    # Run Phase 1 pipeline (4 hours 4 minutes)
    cd /home/dibyanayan/jashneet/SR-NLE
    source /home/dibyanayan/jashneet/sr-nle-test/bin/activate
    python PCR/src/runners/pcr_phase1_runner.py --model_name qwen --max_iters 3

    # Evaluate results (instant, no GPU needed)
    python PCR/src/evaluation/faithfulness.py --model_name qwen


================================================================================
NEXT STEP: PCR PHASE 2
================================================================================

    Phase 2 runner : PCR/src/runners/pcr_phase2_runner.py  (to be built)
    Key addition   : get_margin() in model.py (already implemented)
    New prompts    : get_critique_prompt_phase2() and get_ce_refinement_prompt()
                     (already implemented in comve_prompts.py)

    Expected improvement: faith rate > 53.62%
    Mathematical basis  : Delta_t = P(y|DE) - P(y'|DE) >= tau (0.95)
"""


def print_summary():
    print("=" * 60)
    print("PCR PHASE 1 — QUICK SUMMARY")
    print("=" * 60)
    print()
    print("  Input  : 235 items from SR-NLE's explanation_gd.json")
    print("  Output : PCR/experiments/.../pcr_phase1.json")
    print()
    print("  PIPELINE:")
    print("    Step 1  Set up DE (SR-NLE explanation) + labels y, y_prime")
    print("    Step 2  Generate CE (counterfactual explanation for y_prime)")
    print("    Step 3  ME check: Are DE and CE mutually exclusive? YES/NO")
    print("    Step 4  If NO  → Critique DE + Critique CE")
    print("            If YES → Converged, stop")
    print("    Step 5  Repeat up to 3 times")
    print()
    print("  ITERATION BREAKDOWN:")
    print("    iter 0 (no refinement needed) :  98 items")
    print("    iter 1 (1 critique round)     :  28 items")
    print("    iter 2 (2 critique rounds)    :   9 items")
    print("    iter 3 (hit max, not converged): 100 items")
    print()
    print("  RESULTS:")
    print("    SR-NLE best (iter 2) : 86/235  = 36.60%")
    print("    PCR Phase 1          : 126/235 = 53.62%")
    print("    Improvement          : +17.02% over SR-NLE")
    print("    Regressions          : 0")
    print()
    print("  SAVED:")
    print("    PCR/logs/df/pcr_phase1_faithfulness.csv")
    print()
    print("  NEXT: PCR Phase 2 (probability margins)")
    print("=" * 60)


if __name__ == "__main__":
    print_summary()
